{
 "title": "Robot dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Логи database-worker",
   "type": "logs",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"database-worker\"} |= ``"
    }
   ]
  },
  {
   "title": "Логи metrics-adapter",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"metrics-adapter\"} |= ``"
    }
   ]
  },
  {
   "title": "Логи robot",
   "type": "logs",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"robot\"} |= ``"
    }
   ]
  },
  {
   "title": "Логи stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"stream\"} |= ``"
    }
   ]
  }
 ]
}