{
 "title": "Trade Stream Service Dashboard",
 "description": "Метрики сервиса по обработке стрима сделок",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Время синхронизации тикеров",
   "type": "gauge",
   "description": "Сколько времени занимает синхронизация тикеров с биржей",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trading_latency_seconds{module=\"syncsymbols\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время добычи тикеров",
   "type": "gauge",
   "description": "Сколько наносекунд занимает добыча списка тикеров",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trading_latency_seconds{service=\"tradestream\", module=\"getsymbols\"}",
     "legendFormat": "Время добычи тикеров, ms"
    }
   ]
  },
  {
   "title": "Скорость стрима",
   "type": "timeseries",
   "description": "Примерное число сделок в секунду",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flow_speed_per_second{module=\"streammessages\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "logs",
   "description": "Логи Trade Stream Service",
   "gridPos": { "h": 20, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"trade_stream_service\"} |= ``"
    }
   ]
  },
  {
   "title": "Среднее время обработки сделки",
   "type": "timeseries",
   "description": "Сколько занимает обработка сделки",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "trading_latency_seconds{service=\"tradestream\", module=\"tradehandle\"}",
     "legendFormat": "Среднее время обработки сделки, µs"
    }
   ]
  }
 ]
}